Feat add listscreen
SergioEtreros/FurryFriendFinder pull request #22
Opened 2024-06-11 09:35 UTC by DevDCruz

## Pull Request Typology
This is a PR of type feat

## Details and functionality
This PR introduces the basic components of the list screen and coil implementation.

## Add screenshot if pertinent

![image](https://github.com/SergioEtreros/FurryFriendFinder/assets/115178067/20440ca0-4105-4bda-a09d-1dda957ab7c9)

## More information
Hago el pull request con el objetivo principal de ir completando la navegación. Se que habrá que cambiar mucho, pero creo tampoco puedo hacer mucho mas sin el ViewModel y no se si debería crearlo antes de realizar el PR, ya que no se si forma parte de esta feature o sería una independiente. Todo el contenido esta hardcodeado mientras completo lo anterior. 
Con esto pretendo que podamos ir modelando a gusto de todos como mostrar el listado. Toda recomendación, consejo o crítica que podáis ofrecer será gratamente bienvenida.

2024-06-11 15:16 UTC, SergioEtreros requested changes

2024-06-11 15:16 UTC, SergioEtreros commented on app/src/main/java/com/codersgroup/furryfriendfinder/ui/screens/list/ListScreen.kt
> +fun InfoListItem(onClick: () -> Unit) {
Este onClick debería navegar hasta la navegación con el id de la mascota clickada para poder llamar al detalle con ese id, por lo que tendría que ser un parámetro de la listscreen

2024-06-11 15:16 UTC, SergioEtreros commented on app/src/main/java/com/codersgroup/furryfriendfinder/ui/screens/list/ListScreen.kt
> +        Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.background) {
el Surface y el theme no te harían falta porque ya están en el main y todo va dentro de ellos, si lo quieres poner para poder probar como se vería los puedes poner en la preview, pero aquí no son necesarios

2024-06-12 10:41 UTC, DevDCruz commented on app/src/main/java/com/codersgroup/furryfriendfinder/ui/screens/list/ListScreen.kt
> +        Surface(modifier = Modifier.fillMaxSize(), color = MaterialTheme.colorScheme.background) {
Si lo estuve hanlando con Joel, lo he puesto para poder hacer el pantallazo y se viera como pantalla. Lo borro.

2024-06-12 10:44 UTC, DevDCruz commented on app/src/main/java/com/codersgroup/furryfriendfinder/ui/screens/list/ListScreen.kt
> +fun InfoListItem(onClick: () -> Unit) {
vale, lo meto entonces como parámetro de listScreen y dejo la función vacía para completarla cuando tengamos la app mas desarrollada.

2024-06-13 19:36 UTC, SergioEtreros approved these changes

2024-06-15 16:44 UTC, VictorDVLP approved these changes

2024-06-24 09:05 UTC, lintz18 approved these changes

2024-08-31 12:21 UTC, merged